# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - simicodepushserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./api # Ensure to run commands in the 'api' folder

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* # Zip the content of the 'api' folder
        working-directory: ./api # Ensure zipping happens in the 'api' folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app # Artifact name must match in the deploy step
          path: release.zip # Upload the zip artifact created

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Ensure the artifact name is correct

      - name: Unzip artifact for deployment
        run: unzip release.zip # Unzip the artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DFB8F80735F4F13A91940F439513E51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_330AD0852EAD4450951BAE97A532CF65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4961AC12B5DE49FEAF65975D8A72BF2D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'simicodepushserver'
          slot-name: 'Production'
          package: ./api # Ensure deployment is from the 'api' folder
